spring:
  application:
    name: cooperfilme
  datasource:
    url: jdbc:h2:mem:cooperfilme
    driver-class-name: org.h2.Driver
    username: cooperfilme
    password: 123
  h2:
    console:
      enabled: true
      path: /h2/console
  jpa:
    show-sql: true